# -- Main Menu --
# https://blowfish.page/docs/configuration/#menus

[[main]]
  name = "Research"
  pageRef = "research"
  weight = 20

[[main]]
  name = "Publications"
  pageRef = "publications"
  weight = 30

[[main]]
  name = "Blog"
  url = "https://qiita.com/bakanaouji"
  weight = 50

# -- Footer Menu --
# (left empty; footer menu is disabled in params.toml)
