baseurl = "https://bakanaouji.github.io/"
title = "Kenshi Abe"
publishDir = "docs"
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.
googleAnalytics = "UA-150920247-1"

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "bakanaouji" # Enable or disable Disqus.

[params] # theme parameters
    author = "Kenshi Abe" # Author's name.
    info = "Research Scientist of Learning in Games" # Author's job title or info.
    description = "Kenshi Abe's personal website" # Site description.
    keywords = "portfolio,researcher,personal" # Site keywords.
    avatarurl = "/logo.jpeg" # Contain the path of the optionnal avatar in the static folder.

    #footercontent = "Enter a text here." # Add footer content
    fixedbarContent = "Do you want to get in touch with me? →" # Add fixedbar content
    fixedbarContentAfter = "Thank You! Please share it if you like it→" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = ["custom.css"]

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = false  # new add
    enableFacebookShare = false # new add
    enableHatenaShare = false   # new add
    enableLineShare = false     # new add
    enableLinkedInShare = false # new add

    # thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/bakanaouji/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/bakanaouji/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/kenshi-abe/"
[[params.social]]
    name = "Email"
    icon = "fas fa-envelope"
    weight = 4
    url = "mailto:abekenshi1224@gmail.com"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about"
[[menu.main]]
    name = "Works"
    weight = 2
    url = "/works"
[[menu.main]]
    name = "Blog"
    weight = 3
    url  = "https://qiita.com/bakanaouji"

# Goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true